__version__: 1.1.2
actor_adam_eps: 0.0001
actor_batch_size: 16
actor_grad_norm_clipping: 1200
actor_learning_rate: 0.0004
actor_ordinal: false
actor_unroll_len: 20
actor_use_rms: false
auto_res: true
base_seed: 1
baseline_cost: 0.5
buffer_traj_len: 50
ckp: false
ckpdir: ../logs/thinker/drc_check3
cmd: thinker/train.py --use_wandb true --xpid drc_check3 --drc true --actor_unroll_len
  20 --reg_cost 1 --actor_learning_rate 4e-4 --entropy_cost 1e-2 --v_trace_lamb 0.97
  --actor_adam_eps 1e-4 --project thinker
critic_enc_f_type: 0
critic_enc_type: 0
critic_zero_init: true
cur_cost: 0.0
cur_cost_anneal: true
cur_done_elapse: 0
cur_done_gate: true
cur_ema: 0.999
cur_enable: false
cur_enc_cost: 1.0
cur_norm_type: 0
cur_pi_cost: 0.0
cur_return_norm_type: -1
cur_reward_adj: -1
cur_reward_bn: 200000
cur_reward_cost: 0.0
cur_reward_lq: 0.05
cur_reward_max: 1000.0
cur_reward_min: 0.0
cur_reward_mq: 0.5
cur_reward_norm: true
cur_reward_pri: true
cur_reward_uq: 0.95
cur_sup_cost: 0.0
cur_v_cost: 0.0
cur_x_cost: 0.0
detect_dan_num: 0
discounting: 0.97
discrete_k: -1
drc: true
dual_net: true
entropy_cost: 0.01
env_n: 64
float16: false
git_revision: 91f8dd61c4d673425b6dbd2d154684fdc99882da
gpu_learn: 0.5
gpu_learn_actor: 0.25
gpu_self_play: 0.25
grayscale: false
has_action_seq: true
im_cost: 0.0
im_cost_anneal: true
im_enable: false
im_entropy_cost: 0.0001
last_layer_n: 0
legacy: false
max_depth: 5
max_replay_ratio: 6
min_replay_ratio: 5
model_batch_size: 128
model_buffer_n: 200000
model_disable_bn: true
model_done_loss_cost: 1.0
model_downscale_c: 2
model_enc_f_type: 0
model_enc_type: 0
model_grad_norm_clipping: 0
model_has_memory: false
model_img_loss_cost: 10.0
model_img_type: 1
model_learning_rate: 0.0001
model_logits_loss_cost: 0.5
model_mem_unroll_len: 0
model_noise_loss_cost: 0.0
model_ordinal: false
model_reg_loss_cost: 0.0
model_return_n: 5
model_rs_loss_cost: 1.0
model_self_bootstrap: false
model_size_nn: 1
model_sup_loss_cost: 0.0
model_unroll_len: 5
model_vs_loss_cost: 0.25
model_warm_up_n: 200000
model_zero_init: true
name: Sokoban-v0
noise_alpha: 0.8
noise_d: 10
noise_enable: false
noise_mlp: false
noise_n: 16
one_to_threed_state: false
parallel: true
parallel_actor: true
policy_vis_freq: -1
policy_vis_length: 20
preload: ''
preload_actor: ''
priority_alpha: 0.6
priority_beta: 0.4
profile: false
project: thinker
ray_cpu: -1
ray_gpu: -1
ray_mem: -1
real_state_rnn: false
rec_t: 1
reg_cost: 1.0
repeat_action_n: 0
require_prob: true
reset_mode: 0
return_double: false
return_h: false
return_norm_type: -1
return_x: false
reward_clip: -1.0
sample_n: -1
sample_replace: true
sample_temp: 4
savedir: ../logs/thinker
se_buffer_n: 10
se_lstm_table: false
se_manual_stat: false
se_query_cur: 0
se_query_size: 5
se_td_lambda: 0.9
se_tree_carry: false
see_h: false
see_real_state: true
see_tree_rep: false
see_x: false
self_play_n: 1
sep_im_head: true
stat_mask_type: 0
test_rec_t: -1
total_steps: 50000000
train_actor: true
train_model: false
tran_attn_b: 5
tran_dim: 128
tran_head_n: 8
tran_layer_n: 3
tran_lstm_no_attn: false
tran_mem_n: 40
tran_t: 1
tree_carry: true
tree_rep_rnn: true
use_wandb: true
v_trace_lamb: 0.97
wandb_ckp_freq: 500000
wrapper_type: 1
x_enc_first_pool: true
x_rnn: false
xpid: drc_check3
